name: Build and deploy native image
on: [push, pull_request]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: probe
              run: ls -l
            - name: Permisos
              run: chmod 777 *.*
            - name: Login to Azure
              uses: azure/login@v1.1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
            - name: 'Deploy to Azure Function'
              uses: Azure/functions-action@v1.1.5
              with:
                app-name: ${{ secrets.AZ_FUNCTION_NAME_APP }}
                package: ./














